POST http://localhost:65000/ HTTP/1.1
Content-Type: application/json

{
    "table" : "EmployeeDetails",
	"request" : "view",
    "data" : {
                    "FirstName": "Testing",
                    "LastName": "Vance",
                    "EmpEmail": "Testing@teamthreshold.onmicrosoft.com",
                    "EmpPassword": "password",
                    "isAdmin": false,
                    "LocationID": "1C2"
                }
}
